dist: trusty

language: node_js

node_js:
  - "8.9.1"

before_install:
  - npm i -g greenkeeper-lockfile@1

install:
  - npm i

before_script:
  - greenkeeper-lockfile-update

script:
  # - npm run validate

after_script:
  - greenkeeper-lockfile-upload
